# The change log, in one place. sources.html renders all of it; the home page
# shows the most recent few. Typed by what changed, so a correction is never
# mistaken for an addition.
#
# kind: "Correction" | "Addition" | "Source refresh"
ENTRIES = [
    dict(kind="Correction", date="1 Sep 2026", title="Sky's dearest boss was a lower bound printed as a figure",
         body="The Plane of Sky pages published <strong>35,946 damage to kill</strong> for Bazzt Zzzt, and <a href=\"learn/difficulty.html\">the difficulty explainer</a> published <strong>23,321</strong> for the same boss at the same tier. <strong>Both came from our own measured data and one of them was a floor.</strong> A fight the parser marks <em>damage_is_floor</em> was joined after the boss was already engaged, so its total is a lower bound rather than a measurement. The Sky pages took the largest total observed, which silently preferred those partial fights: <strong>on six of the eight ring bosses the number printed was a floor sitting ABOVE the fullest complete view of the same kill.</strong> <strong>The comparison built on it moved with it.</strong> Sky&rsquo;s cost against Cazic-Thule at Refined read <em>about a 10th</em>; against the fullest view it is <strong>about a 16th</strong>. That sentence was never typed &mdash; it is computed from the figure &mdash; so it was wrong for exactly as long as its input was, and it corrected itself the moment the input did. <strong>The fix is a choice made once instead of twice.</strong> Both pages had computed their own maximum over the bosses, and agreed only because they made the same mistake; the dearest boss is now derived a single time in the dataset and read from there. <strong>CLAUDE.md has said since 11 August to trust the fullest view of a boss at a tier and treat the rest as lower bounds.</strong> The field holding that view had been in the data all along with nothing reading it"),
    dict(kind="Correction", date="31 Aug 2026", title="Three claims, one source, one badge",
         body="The multiclass entry on <a href=\"learn/still-true.html\">what is still true</a> made three statements: characters run three classes at once; two at creation, a third at 10, locking at 11; and <strong>the active trio uses the level of its lowest class</strong>. It carried <strong>one</strong> piece of evidence, badged <strong>tier 1</strong>, marked <em>Settled</em>. <strong>That evidence speaks only to the lock</strong> &mdash; unlock tokens priced in the Producer&rsquo;s Letter of 8 July 2026, which only makes sense if the choices lock. It says nothing about what level a trio runs at, so the third claim was published at this site&rsquo;s highest confidence on a source that does not address it. <strong>The page states this rule in its own header and broke it:</strong> <em>&ldquo;What an entry may never be is confidently resolved on evidence that does not support it.&rdquo;</em> Two entries there exist because somebody else did this. <strong>The fix is a split, not a downgrade.</strong> The structure keeps tier 1, and its evidence now says it covers the structure and nothing beyond. The trio&rsquo;s level becomes its own entry, <strong>open, with no tier</strong> &mdash; <em>not recorded</em>, which is what this site writes when it has read nothing. A lower badge would have invented a confidence nobody holds. <strong>It was not deleted, deliberately:</strong> the claim may well be right, and removing it would lose the question along with the error. One read of that Producer&rsquo;s Letter settles it either way, and the entry now says so"),
    dict(kind="Correction", date="30 Aug 2026", title="We published this criticism of somebody else&rsquo;s application while doing it on 715 pages",
         body="This site tells readers, about a collaborator&rsquo;s application, that it <strong>&ldquo;fetches its typeface from Google each time it launches, which discloses your IP address to Google&rdquo;</strong>. That sentence is true, it was measured, and it stays up. <strong>715 of our 717 published pages did exactly the same thing</strong> &mdash; two requests to <code>fonts.googleapis.com</code> and one to <code>fonts.gstatic.com</code>, before anything rendered, on every page. <strong>The only two files that did not were the two application bundles built to be self-contained.</strong> <strong>Several of the pages doing it said they were not.</strong> The lockout tracker&rsquo;s page printed <em>Nothing transmitted</em>; the tools index printed it above all seven cards, next to <em>Works offline</em>. So the page carrying the accusation committed the thing it accused, and a reader could have checked that sentence against the page it was printed on at any time since it was written. <strong>The asymmetry is worse than equal scale, and this is the part worth saying rather than softening.</strong> Four of the five windows in that application request nothing at all; the fetch is scoped to one of them, which our own sentence said. Ours was on 715 of 717. <strong>Their scoping was tighter than ours while we described the fault as theirs.</strong> <code>scripts/contamination.py</code> exists in this repository because <em>a scanner that only finds other people&rsquo;s rot is an attack ad</em>, and this is that failure in its purest available form. <strong>Two sessions found it within the same hour and neither was looking for it.</strong> Nothing was watching: the tool that loads every page in a real browser aborts every non-local request, so it had measured a site whose remote fetches never happened, every run since it was written. <strong>The fix is that the disclosure stops existing rather than being disclosed better.</strong> All four typefaces are open-licensed and are served from this origin now, byte-identical copies with the licences beside them, and no published page fetches from another origin at all. <strong>The claim was also split, because two promises were being spoken as one.</strong> <em>Your log never leaves this machine</em> is about egress, is true, and stays true wherever the code is embedded &mdash; the tools here have no transmit path. <em>This page makes no network requests</em> is about one file, and does not survive that file being replaced. Three of the four sentences on this site were the second kind while reading as the first. That distinction is Session D&rsquo;s, drawn about its own work before it applied to ours"),
    dict(kind="Correction", date="20 Aug 2026", title="Our share cards advertised a 3D model we deleted, and walls we never had",
         body="The picture Discord shows when anyone pastes a link here is generated, not photographed, and two of those pictures were wrong. <strong>The raids card read &ldquo;Positioning in 3D &middot; Model: turn it, phase it&rdquo;</strong> &mdash; selling an interactive encounter model that was withdrawn on 17 August, three days before anyone noticed the card was still selling it. It was the image on both raid pages, so it is what every shared raid link has shown since. <strong>The dungeons card read &ldquo;walls drawn from the game&rsquo;s own files&rdquo;.</strong> There are no walls in our data: the floor plans are read from the game&rsquo;s meshes as walkable-floor outlines, and the word &ldquo;wall&rdquo; does not appear anywhere in the geometry we hold. Both are corrected, and the raid card now counts the bosses actually measured rather than describing a feature. <strong>The interesting part is why the earlier fix missed them.</strong> On 18 August every <em>figure</em> on these cards was made derived rather than typed, precisely because a share card cannot be reached once it is posted. That fix worked and still holds. But the taglines beside those figures are typed prose, and nothing had been said about those &mdash; so the card kept its honest numbers and its dishonest sentence. <strong>A rule that covers the numbers does not cover the words next to them</strong>, and a withdrawal that stops at the code leaves the advertising running"),
    dict(kind="Addition", date="20 Aug 2026", title="Whether a raid boss heals itself looks like a property of the boss, not the difficulty",
         body="This site has recorded since 11 August that self-healing is <strong>not</strong> gated behind a difficulty tier &mdash; Lady Vox heals herself in the open world at base, and Cazic-Thule sixteen times at the third tier. <strong>That was right about the tier and incomplete about the kit.</strong> Thirty measured fights across the five Plane of Hate bosses split cleanly in two, and the split does not move with difficulty: <strong>Coercer T&rsquo;vala, Mistress of Scorn and Maestro of Rancor have never been seen to heal themselves in any fight</strong>, across nineteen kills, including the fullest views of each &mdash; fourteen attackers, where a thin view could not hide a heal. <strong>Master of Spite and Lord of Ire demonstrably do.</strong> So the question is not what the tier unlocks; it is what the individual boss carries. <strong>The asymmetry is the whole finding and it is worth stating plainly.</strong> A heal seen proves the kit has one. A heal not seen proves very little. And the heal counts do <em>not</em> track how much of a fight one client witnessed, which is the rule that explains damage totals: Lord of Ire&rsquo;s fullest view records <strong>zero</strong> self-heals and its thinnest records <strong>six</strong>, exactly backwards. A sentence claiming otherwise was written here and withdrawn when the dataset was re-read rather than remembered. <strong>Thirty fights is a sample, not a proof</strong>, and the figures are read out of the measured dataset rather than typed beside it"),
    dict(kind="Correction", date="20 Aug 2026", title="A number cut in half published as a whole one",
         body="Najena&rsquo;s page said <strong>the NPC record says 3</strong>. The record says <strong>35</strong>. Her notes were shortened to fit a fixed length and the cut landed between the two digits, so the site asserted a level for a named mob that no source states. <strong>Every other shortening on this site is a rough edge a reader can see; this one was a false figure they could not</strong>, because a severed number does not look severed &mdash; it looks like a whole, smaller number. That is the single case where trimming text turns into inventing a fact, and it is now guarded specifically: text is cut on a word boundary, trailing words are dropped until the last does not end in a digit, and the cut is marked with an ellipsis so a reader can see something was removed. <strong>Three places were doing the same hard cut and only one of them was visible.</strong> The item and mob pages each shortened the field once, and the description that travels to search engines and share cards shortened the already-shortened copy again &mdash; so the fault had two chances to land on a digit and one of them was off-page entirely. All three now share one rule. <strong>It is checked rather than remembered.</strong> The build refuses any shortened field whose cut lands on a digit, and reports how many fields it examined, because &ldquo;none of these ends on a digit&rdquo; is satisfied for free by examining nothing"),
    dict(kind="Correction", date="20 Aug 2026", title="The wrong-number-of-zones correction had missed one page",
         body="The 18 August correction below replaced <strong>eleven dungeons</strong> with the six the patch note actually names, on every survey and in every per-zone source record. <strong>One page kept the old number.</strong> The explainer on reading the floor plans still told readers the note removed placeholders from eleven dungeons, five days after the site had established it names six, and it read as current because nothing on it was marked as stale. <strong>A correction applied in one place instead of all of them is the fault this site keeps finding in its own work</strong>, and the repair is the same one every time: the sentence now counts and names the six zones from the source records rather than carrying a number somebody typed, so it cannot drift from them again. The paragraph also now says plainly that other zones had placeholders removed on weaker evidence and that their surveys say which, which the old sentence left out"),
    dict(kind="Correction", date="18 Aug 2026", title="Our most-repeated sourcing claim named the wrong number of zones",
         body="This site has said, on ten survey pages at once, that the 28 July launch-day patch note removed named-mob placeholders from <strong>eleven dungeons</strong> &mdash; or in the field every one of those pages read from, &ldquo;all ten of these zones and Upper Guk&rdquo;. <strong>The note names six.</strong> The Hole, Nagafen&rsquo;s Lair, Lower Guk, Lair of the Splitpaw, The Warrens and Castle Mistmoore. It does not mention Upper Guk at all. It was read in a real browser on 18 August and is now stored verbatim in the repository, because the note is rendered by JavaScript and a plain fetch returns nothing but navigation &mdash; which is a large part of why nobody had checked it. <strong>Four zones were carrying the flag on a note that does not name them, and they do not all lose it.</strong> Najena keeps the claim on the 23 June revamp note its own survey has quoted since it was written; that note is no longer published anywhere we can reach, and the page now says so. Befallen and Blackburrow keep it on a dated eqlwiki category revision that names them explicitly &mdash; tier 2, not a patch note, and the pages say that too. <strong>Crushbone loses it outright.</strong> No source names Crushbone, so its placeholder rows are live again rather than struck through with a tooltip citing a patch note that never mentioned the zone. <strong>The bare boolean was the real defect.</strong> One <code>placeholders_removed: true</code> was covering a tier-1 patch note, a tier-2 wiki revision and nothing at all, and could not tell them apart &mdash; the same shape as the Sky tracker flag this project already records as its canonical lesson. Each zone now names a source id, the sources carry their own tier, url and read-date, and the confidence a page shows is derived from that rather than typed beside it. <strong>It also closed a question this site has carried since 11 August</strong>, which said in as many words that one reading of the developers&rsquo; own page would settle whether Blackburrow was in the pass. It was not"),
    dict(kind="Correction", date="18 Aug 2026", title="Three tools withdrawn, because one tool does all three jobs better",
         body="The <strong>character sheet</strong>, the <strong>planar gear tool</strong> and the <strong>inventory reader</strong> are gone. <a href=\"tools/50-upgrades.html\">50 Upgrades</a> supersedes all three, and not narrowly: it works a trio&rsquo;s eligibility as the union of three classes, covers every slot rather than the seven armour slots, models every item from +0 to +10, and reads an inventory export for itself. Each of ours did one of those things against a smaller catalogue. <strong>Keeping a worse copy of something already available is the rule this site applies to other people&rsquo;s tools</strong> &mdash; the reason we link eqlegendstools for items and eqlwiki for travel rather than rebuilding them &mdash; and it has to apply to ours or it is not a rule. The old addresses redirect to the tool that replaced them, in both forms, and there is no tombstone page: a removal belongs in a change log, not in a page that exists to announce its own absence. <strong>Two things that look like they went and did not.</strong> The planar item records still drive <a href=\"sets/index.html\">every planar set</a>, and they still feed the measured-drop matcher &mdash; without them every planar set drop is discarded as trash, which is how the only evidence of which boss drops which set would have vanished. The item-name-to-ID table still publishes as <code>items.v1.json</code>. Both were written by generators that also rendered a page, and both were separated from those pages first, deliberately, so that this removal could not take a dataset with it"),
    dict(kind="Correction", date="18 Aug 2026", title="We printed one of the planner&rsquo;s counts under another one&rsquo;s name",
         body="The 50 Upgrades page led with an item count labelled <em>Items shipped</em>. The number was read from the planner&rsquo;s own published snapshot, never typed, from a file recording its source and the date it was read &mdash; the rule followed exactly. <strong>It was still the wrong quantity.</strong> The figure came from the field counting items that survived the planner&rsquo;s era purge, not the field counting what its catalogue holds. The two were identical, so nothing could tell them apart, and they stopped being identical the moment ten items were admitted on evidence other than era. <strong>A vendored number that does not say which field it is will be read as the wrong quantity eventually.</strong> Every figure in that snapshot is now keyed by its exact path in the planner&rsquo;s file and the page looks each one up by that path, so the field sits beside the label where a mismatch is visible, and a field that moves upstream stops the build instead of publishing a plausible wrong number. The page now prints the catalogue size and states separately how much of it is there on era and how much on independent evidence. <strong>Two other things moved with the refresh.</strong> The share of the catalogue carrying no source standing was written as a word, beside a computed value nothing used, and the refresh moved it &mdash; it is printed now. And the licence: this site withdrew the planner&rsquo;s unsourced <code>CC BY-SA 4.0</code> claim on 18 August while leaving the snapshot carrying what they said, because the difference between what we can stand behind and what they claimed was the point. The planner has since withdrawn it too, so there is no longer a difference to draw"),
    dict(kind="Source refresh", date="18 Aug 2026", title="The 18 August patch notes, and what they change here",
         body="Daybreak published update notes dated <strong>18 August 2026</strong>. They are tier 1, which puts them above every wiki page this site reads. <strong>Castle Mistmoore was revamped.</strong> Named NPCs are now guaranteed spawns; each of them now drops a common or rare item with stat bonuses, some familiar and many new; every named in the zone is designated a rare creature, which the notes say greatly increases the chance of dropping motes of potential; and the castle&rsquo;s residents are less aggressive by day and no longer react from extreme ranges, with night unchanged. <strong>Those are three of the things that survey is about &mdash; named spawns, named loot and aggro range &mdash; and every measured figure on the page predates all of them.</strong> The survey drops from <em>verified</em> to <em>partial</em> and now names its open gate: gates 1 and 2 are about sourcing and still stand, gate 3 is open because nobody has checked whether the mesh moved. One logged session in the revamped zone closes it. <strong>Separately, the notes fix high-level named in Kedge Keep taking &ldquo;an excessively long time to respawn&rdquo;.</strong> That lands on a gap carried here since 28 July, when maximum respawns were lowered without figures being published and the affected surveys began stating pre-patch timers as ceilings. It also lands on the one zone where we hold nothing of our own: Kedge Keep is ungraded, with no session logged in it at all. <strong>No figure was published this time either</strong>, so the ceiling stands and now has a second reason to be wrong. <strong>Nothing else on this site has been adjudicated against these notes.</strong> They also move a shadow knight lifetap from level 8 to level 5, add another at level 10, change how charm behaves and retune two Plane of Sky mobs. Reading them across thirteen surveys is a claim-by-claim pass against a source that outranks the pages several of those claims came from, and it has not been done. Until it is, every survey is current to its own recorded date rather than to today"),
    dict(kind="Correction", date="17 Aug 2026", title="Two things we published that are not in the game",
         body="Castle Mistmoore&rsquo;s roster carried <strong>Mayong Mistmoore</strong>, and its loot table a <strong>Fanged Skull Stiletto</strong> said to drop from him. Both had a page of their own. <strong>Neither is in the game.</strong> No measured session in that zone has ever recorded him as a mob, and the stiletto has never been recorded dropping anywhere. Both pages are withdrawn and their addresses redirect to the survey rather than answering 404. <strong>The faction named after him is real</strong> &mdash; killing in the castle moves it, and the survey still says so. <strong>Removing the row also closed a flagged gap, and closed it the wrong way round:</strong> it read <em>level and coordinate unconfirmed</em>, and we had been carrying that as evidence still to find. It was not. A gap that closes because its subject does not exist has not been answered, and the distinction is the difference between a record and a tidy page"),
    dict(kind="Correction", date="17 Aug 2026", title="The navigation maps are withdrawn",
         body="Five zones carried a second page beside the survey: a hand-made navigation map. <strong>Every survey now draws its floor plan from the game&rsquo;s own mesh</strong>, which separates the storeys and checks each plotted coordinate against walkable floor before it prints. A hand-drawn map of the same zone sitting next to that is a worse copy of something already on the page, and not shipping one is a rule here. The five addresses redirect to the surveys they belonged to &mdash; they were linked from the dungeon index for weeks, and someone will have one open"),
    dict(kind="Addition", date="17 Aug 2026", title="One format for every survey",
         body="Each survey had grown its own layout, so a reader who learned one had to learn the next. <strong>They are one format now</strong>, the raid pages with them: the same header strip, the same roster and loot tables, the same rail for cautions. Three things went with the change. <strong>Measured sections no longer publish session counts, session windows or character names.</strong> <strong>Experience per kill is gone from the site entirely</strong> &mdash; experience is a function of the reader&rsquo;s level, so a figure measured at one level tells a stranger at another nothing true. And <strong>the tier M badge now carries the provenance</strong>: it already means we verified this in play, so a sentence beside it proving the measurement had happened was doing no work. The rule throughout is to keep the fact and drop the tally, never to drop the finding"),
    dict(kind="Addition", date="17 Aug 2026", title="Sky Ledger, and the end of our own Sky tracker",
         body="<a href=\"tools/sky-ledger.html\">Sky Ledger</a> reads your own combat log and says which of the 95 Plane of Sky class-unlock tests you can hand in now. It runs in a browser with nothing installed and nothing uploaded, or as an overlay on the game. <strong>It is promoted above the atlas for one reason, and it is a correctness property rather than a nicer surface: a turn-in piece can only be spent once.</strong> 29 of the 128 turn-in items are wanted by more than one test and all 15 wind runes are among them, one of them by seven separate tests. Hold one and exactly one test can be finished with it. <strong>Every other tracker counts that item against every test that wants it &mdash; ours did</strong>, and told you several quests were ready when one was. Sky Ledger pools what you hold and spends each unit on the test closest to done. <strong>So our Plane of Sky tracker is withdrawn rather than kept beside it</strong>: two Sky trackers is the &ldquo;which do I use&rdquo; question, and after that property the older one is the wrong answer. <code>/tools/plane-of-sky.html</code> redirects to the new page and there is no tombstone. It also holds this site&rsquo;s standard on its own: it refuses to publish a drop rate it cannot measure, prints a dry streak as a bound &mdash; <code>&lt;28% &middot; 0/9</code>, never <code>0%</code> &mdash; reports what it could not place rather than quietly dropping it, and checks its parsing against the client&rsquo;s own string table rather than against 1999. <strong>The app is served under a content hash</strong>, because a stale cached copy of a log parser is not visibly stale &mdash; it is the fault the stylesheet had on 16 August, in a worse place"),
    dict(kind="Correction", date="17 Aug 2026", title="We have withdrawn the Eye of Veeshan guide entirely",
         body="It was the most elaborate page on this site &mdash; a 3D encounter model you could orbit, a tank rotation, a phased pull. <strong>Its central tactic was never necessary.</strong> The whole guide was built around not keying a raid to island 8: bring the boss down to island 7, where your force already stands after Sister of the Spire, because <em>almost nobody keys a full raid to Island 8</em>. <strong>In play it is killed where it spawns.</strong> <strong>The pull-down was inherited Project 1999 text and we published it as a current strategy, in three dimensions, with a diagram.</strong> That is the most confident this site has ever been about something it had not checked, and the presentation is exactly what made it convincing. The page is gone rather than corrected: once the tactic goes, what remains is a stat block we had already struck and a model of a fight nobody has. <strong>What we actually measured survives</strong> on <a href=\"raids/plane-of-sky.html\">the Plane of Sky page</a> &mdash; the measured kills and the melee sample that contradicts both inherited damage figures. The lesson is not about this boss. <strong>A 3D model is an assertion with production values</strong>, and we built one on top of a sentence from 1999"),
    dict(kind="Correction", date="15 Aug 2026", title="The Plane of Sky is not a raid zone",
         body="Every reference in this community describes a zone that needs a full raid, and <a href=\"raids/plane-of-sky.html\">our page said it too</a>. <strong>It is wrong.</strong> Fifteen of Sky&rsquo;s bosses are measured, and <strong>the most expensive of them costs 26,158 damage</strong> against Cazic-Thule&rsquo;s 382,035 at Refined. That is a fifteenth of one plane god, and it falls to a group rather than a raid. A reader planning a night in Sky was being told to assemble people they do not need. <strong>The key chain is confirmed for the first time</strong> &mdash; six of its seven predicted drops landed, each from exactly the boss the chain names, and the seventh is unchecked because <strong>the Thunder Spirit Princess has never been recorded here at all</strong>. Two more things no source we hold mentions: <strong>island 6 runs six named bees rather than one</strong>, and they are not a single mob in successive forms as this page claimed &mdash; the Key of Scale comes off Bazzt Zzzt itself. <strong>Every figure here is at base difficulty</strong>, which is the only tier Sky is measured at, and the page says so beside the table rather than in a footnote"),
    dict(kind="Correction", date="15 Aug 2026", title="Two bosses we lost to a capital letter",
         body="The raid parser matches boss names against the log as written, and a name whose own article is lowercase gets capitalised when it starts a sentence. So <em>&ldquo;You slash a dracoliche for 196 points of damage&rdquo;</em> matched and <em>&ldquo;A dracoliche has been slain by&hellip;&rdquo;</em> did not &mdash; and <strong>a fight that never sees its own death line never closes</strong>. We published <strong>the dracoliche at 1,287 damage at Adaptive and 14,483 at Fused</strong>. The fullest views are <strong>85,671 and 285,202</strong>, plus <strong>a Refined kill at 362,687 that we held no record of whatsoever</strong>. That is not a small mob; it is in the same class as Nagafen and Cazic-Thule, and we had it published as trivial. The same fault hid <strong>the Hand of Veeshan</strong> entirely: island 8&rsquo;s wanderer sat in our data with a full loot table &mdash; the whole efreeti line &mdash; and no fight at all, because its name begins <em>the</em>. It has two now. <strong>Three mobs drop the efreeti gear, not two</strong>, which bears directly on the source conflict an audit flagged on 14 August. Every other boss on the list begins with a capital and none of their figures moved"),
    dict(kind="Correction", date="14 Aug 2026", title="We were grading zones on the wrong thing",
         body="Until today the headline grade on a survey was <code>verify_level</code>, and its third gate asks whether plotted coordinates land on drawn floor. <strong>Plane of Fear and Plane of Hate have no plotted coordinates</strong>, so that gate could never pass there however much we played &mdash; and both scored the same zero as Kedge Keep, where nothing has been measured at all. A grade that cannot tell <em>no coordinates</em> from <em>no evidence at all</em> is not measuring anything. Coordinates are how <em>we</em> draw the floor plans; they are a build input. <strong>Zones are now graded on what a player needs</strong>: the bosses and what they do, the loot and where it comes from, how the difficulty tier changes the fight, which inherited advice is wrong here, and whether it is worth farming. Every facet is computed from the measured data, so a zone improves its grade by being played rather than edited. <strong>The table inverts.</strong> Nagafen&rsquo;s Lair, The Hole, Plane of Fear and Plane of Hate lead at 9 of 10; the four zones the old standard called <em>fully verified</em> &mdash; Najena, Splitpaw, Crushbone and The Warrens &mdash; sit at 4, because no measured session covers them. <code>verify_level</code> is kept, demoted to what it always was: sourcing hygiene"),
    dict(kind="Addition", date="14 Aug 2026", title="Take the data",
         body="Nobody in this community publishes machine-readable data, so every tool re-transcribes the same wiki pages and inherits the same 1999 errors doing it. <a href=\"data/index.html\">Ours is now public</a>: four datasets, versioned, CORS open, no key and no rate limit. <strong>Plane of Sky with a source recorded per claim</strong>, <strong>every drop measured here</strong>, the surveyed zones with their verification state, and item name to game ID. <strong>The version in the filename is a promise</strong> &mdash; fields are never removed and never change type, and anything that would break a reader gets a new number at a new URL while the old one stays up. Values change as evidence improves, which is the product working rather than a breach; each file carries a content hash to cache on. The page states plainly <strong>what this data is not good for</strong>, which is the part nobody else answers: there is no denominator in the sightings file and you cannot compute a drop rate from it. <code>check.py</code> now refuses to publish if a declared field goes missing or a dataset comes out empty"),
    dict(kind="Addition", date="14 Aug 2026", title="We scanned ourselves for classic contamination and published it",
         body="An outside audit found six classic haste figures inside our own <em>verified</em> tier, which is the strongest possible argument that this site needed a tool rather than a habit. <a href=\"learn/contamination.html\">There is one now, and it is pointed here.</a> It found <strong>ten more percentage-haste figures the audit missed</strong>, on four items across three surveys &mdash; the Flowing Black Silk Sash, the Mithril Two-Handed Sword, the Cloak of Flames and the Kitchen Toolbelt &mdash; two of them in the prose that sells the zone, which is where a reader is most likely to believe them. All badged. <strong>Unmarked hits on mechanics we know changed: zero.</strong> A further 302 hits are classic <em>formats</em> rather than errors, counted separately because they measure how much of a page was transcribed rather than how much of it is wrong. <strong>We will not be publishing a league table of anyone else&rsquo;s contamination.</strong> Every site in this community carries inherited classic text, ours included; a scanner that only finds someone else&rsquo;s rot is an attack ad, and the only version worth having is the one that runs here first and publishes whatever it says"),
    dict(kind="Addition", date="14 Aug 2026", title="The tools are now tested by running them",
         body="Every check this site had read the HTML a page <em>ships</em>. Not one ran the page&rsquo;s JavaScript, which is how the Plane of Sky tracker shipped with a dead class picker and 721 green checks. <strong>All eight tools are now executed under a stub browser before anything publishes</strong>, and each must clear two bars: its script runs without throwing, and where a tool renders on load its main control is not empty. Both bars were proved by breaking the tracker on purpose &mdash; once so it throws, once so it silently renders nothing &mdash; and confirming the build refuses each time. The stub is hand-written rather than a dependency, on the same reasoning that keeps three.js vendored here instead of on a CDN. <strong>It cannot tell you a tool looks right or that a button does the right thing</strong>; it tells you the script runs and the page fills. That was the whole gap, and it is worth being plain that opening the page is still the only way to know"),
    dict(kind="Correction", date="14 Aug 2026", title="We broke the Plane of Sky tracker for a day",
         body="Moving the Sky dataset out of the page and into <code>sky.json</code> took one constant with it that nothing noticed: <code>ORDER</code>, the class picker&rsquo;s display order. It sat just past the block that moved. <strong>The picker rendered no classes at all</strong>, so a trio could never reach three and <em>Build character sheet</em> stayed permanently greyed out. It was found by opening the page, which is the only thing that could have found it. <strong>All 721 pages passed our own checks while the tool was unusable</strong>, because every check we had reads the HTML a page ships and none of them run its JavaScript. There is one now: the data constants in these tools are capitalised by convention, and every capitalised identifier a tool&rsquo;s script uses must be declared in that script. It catches this exact fault, and the self-test proves it by removing <code>ORDER</code> and confirming the build refuses"),
    dict(kind="Correction", date="14 Aug 2026", title="Verified is now counted, not asserted &mdash; and five classes qualify, not eleven",
         body="Two days ago the Plane of Sky tracker called eleven classes verified. <strong>Five do.</strong> Nothing about the game changed; we stopped rounding up. <code>verified</code> was one hand-set boolean per class covering its turn-ins, its givers, its reward names, its slots and its stat blocks together &mdash; thirty-odd claims read from different pages on different days &mdash; so a stat block nobody had checked inherited a badge the turn-ins had earned. <strong>Every claim now names its own source, tier and read-date</strong>, and verified is <em>derived</em>: tier 2 or better, nothing marked against it. <strong>Warrior fell out at once</strong>, because its stat blocks were cross-read from a page whose own turn-ins this site had already rejected as classic &mdash; same page, same day, two opposite decisions, and nothing recorded that until now. Where a claim is weak the quest says so in place, naming the source and the date, instead of a badge sitting over the whole class. The dataset also left the markup: it is <code>assets/sky.json</code>, and the build refuses to finish if a claim names a source that does not exist or if one of the five dataset invariants moves"),
    dict(kind="Correction", date="14 Aug 2026", title="Our verified tier was carrying classic data",
         body="An outside audit found six Plane of Sky reward tooltips carrying <strong>percentage haste</strong> &mdash; five of them the identical <em>+41%</em>, which is a copied constant and not five readings. <strong>Legends uses a flat attack-speed value.</strong> All six sat under classes the tracker flagged verified. <strong>The audit is right and this is the worst kind of fault this site can have</strong>, because the badge is the product. The values are <strong>marked suspect in place rather than deleted</strong> &mdash; a marked figure is more useful than a hole. The cause is structural and is now written down: <strong>one boolean per class covers turn-ins, rewards, stat blocks and drop sources at once</strong>, so a stat block nobody had checked inherited a badge that the turn-ins had earned. And the sourcing note listing the verified classes named ten while eleven carried the flag; it prints from the data now"),
    dict(kind="Correction", date="14 Aug 2026", title="Journeyman&rsquo;s Boots drop, and the quest is gone",
         body="Project 1999 text says the boots &ldquo;formerly dropped from Drelzna&rdquo; before being made a quest in October 1999, and that sentence is imported into eqlwiki&rsquo;s <em>Drelzna</em> page where it sits inside a structured NPC record and reads like current data. <strong>They drop.</strong> Reported first-hand on 14 August 2026 &mdash; seen dropping for other players, confirmed by guildmates &mdash; and eqlwiki&rsquo;s own item record agrees. Filed <span class=\"tier tC\">TIER C</span>, because no parsed session here holds a Drelzna kill and a first-hand report is not a parse. An auditor grading our survey made exactly this mistake, reading the classic sentence and not the item record. The survey was right"),
    dict(kind="Correction", date="14 Aug 2026", title="The item count disagreed with itself again",
         body="An audit raised this on 11 August as <em>452 items against 446</em>. We fixed the numbers and not the cause, so it came back as <strong>451 against 441</strong> &mdash; and both were wrong. The home page counted every row, including families and elided fragments that are not items at all; The Index filtered the fragments but not the families; the A&ndash;Z counted the pages it had just written. <strong>There are 435 items</strong>, in 440 rows because a few drop in two zones, plus <strong>6 families</strong> the surveys name as a line rather than piece by piece. A <code>kind</code> field has existed since 11 August to say which is which and not one of the three counts read it. It is counted once now, where the data is made, and <strong>the build refuses to finish if the pages written disagree with the count declared</strong> &mdash; which it did, on the first run, by exactly the six families"),
    dict(kind="Addition", date="14 Aug 2026", title="The plane gods, measured",
         body="The largest gap this site has listed: <em>which kits attach to the plane bosses at D3 and above is recorded nowhere</em>. <strong>Cazic-Thule measured at Adaptive, Fused and Refined; Innoruuk at Fused and Refined</strong>, with ten of Innoruuk&rsquo;s court beside them, and every spell each cast is now on record. <strong>Cazic-Thule runs a shadow knight&rsquo;s kit</strong> &mdash; Harm Touch, Life Leech, Dooming Darkness, Shadow Vortex &mdash; and hits for 38 to 492. <strong>Innoruuk mixes three</strong>: wizard (Ice Comet, Wrath of Al`Kabor), shaman (Malosi, Plague, Gale of Poison) and priest (Superior Healing). That is the published triple-class claim appearing in a log for the first time. Damage to kill: Cazic-Thule 94,941 at Adaptive, 316,488 at Fused, 382,035 at Refined; Innoruuk 333,054 and 345,385. <strong>Every Fear and Hate boss page on the wiki is a Project 1999 import</strong> written before this game existed, so until today nobody had measured any of it"),
    dict(kind="Addition", date="14 Aug 2026", title="Which boss drops which planar set",
         body="The gear tool ranks 116 planar pieces against your trio and could never say where a single one comes from. Now it can: <strong>86 pieces recorded dropping, and every one of the eighteen sets names the mobs measured dropping it</strong>. Seven bosses drop exactly one set each in the data &mdash; Magi P`tasa drops Apothic, Master of Spite drops Rune Etched, Mistress of Scorn drops Imbrued Platemail, Coercer T`vala drops Insidious, Grandmaster R`tal and Innoruuk&rsquo;s Chosen drop Indicolite, and phoboplasm drops Midnight Clad. <strong>Measured sightings, never a rate.</strong> Two faults had been hiding all of it: the drop join only read the dungeon catalogue, which contains no planar piece at all, and it discarded any drop from a mob missing from a hand-written roster &mdash; so measured evidence could only ever confirm what we had already typed. Sightings went from 171 to 524"),
    dict(kind="Correction", date="14 Aug 2026", title="Two gods we never recorded, because we spelled them wrong",
         body="The raid parser has carried a list of boss names since it was written, and two entries on it were guesses: <em>Cazic Thule</em> and <em>Innoruuk</em>. The game writes <strong>Cazic-Thule</strong> with a hyphen and <strong>Innoruuk, the Prince of Hate</strong> in full, so neither ever matched a line. Both gods had been killed repeatedly and the file recorded nothing, because <strong>a boss whose name is wrong is indistinguishable from a boss nobody fought</strong>. Also fixed: two separate kills of the same boss at the same tier were merged into a single fight with an invented range &mdash; Lord of Ire published as &ldquo;61,014 to 401,708, two clients 84.8% apart&rdquo; when only one client was logging at all"),
    dict(kind="Correction", date="11 Aug 2026", title="Those raid kills were never ours alone",
         body="We published Master Yael at five difficulties as <em>&ldquo;killed once at every difficulty by one trio in one session&rdquo;</em>. <strong>Every raid-boss fight on record here is a public pick-up raid, not a trio</strong>, and the damage in each was shared across it. The damage totals are unaffected &mdash; damage to kill counts everyone, and the D4 figure re-checks to 242,060 exactly &mdash; but the sentence beside them was wrong in the direction that misleads hardest. Anyone reading &ldquo;one trio did this&rdquo; and taking a duo into The Hole at Refined would have been badly served. The parser now records the size of a fight rather than assuming it; <strong>the other players are counted and their names discarded</strong>, because nobody is named on this site outside the credits"),
    dict(kind="Correction", date="11 Aug 2026", title="A boss self-heal is not gated at D3",
         body="Beside the same table we said <strong>the kit widens at D3</strong> and <strong>he healed himself never at D0, D1 and D2</strong>. Both were read off one session and later kills contradict the second. <strong>The same boss healed itself at D2 on a separate kill</strong> &mdash; Superior Healing, 210 hit points &mdash; and <strong>Lady Vox heals itself at D0</strong>, at base difficulty. What difficulty raises is how much of the kit turns up, not whether a heal is in it. <strong>And &ldquo;ten times at D4&rdquo; was ten log lines, not ten decisions:</strong> one effect ticking every six seconds for the same 22 hit points. The same shape appears on Lady Vox at her top tier. Counting a recurring drain as ten separate heals overstated what the boss did"),
    dict(kind="Addition", date="11 Aug 2026", title="Lady Vox and Lord Nagafen, at four tiers and two",
         body="<strong>Lady Vox measured at Base, Awakened, Adaptive and Fused</strong>, and <strong>Lord Nagafen at Awakened and Adaptive</strong>. All public raids, all recorded as such. Damage to kill rises with the tier as it does for Master Yael, but <strong>one of these is a fifth of what it should be and is published as a floor rather than a total</strong>: the logging client reached the fight after the boss had already engaged, so the log never saw the opening. That is what a client log is &mdash; a record of what one character witnessed &mdash; and a figure from a fight joined late is a lower bound and nothing more"),
    dict(kind="Addition", date="11 Aug 2026", title="Paste your inventory, and the site reads it back",
         body="<code>/outputfile inventory</code> writes a wall of tab-separated text &mdash; more than half of it empty sockets &mdash; and nobody reads it. The reader turns it into a list of what you carry with everything we know attached: the item&rsquo;s page, its zone, its planar set, and where the drop is <strong>measured rather than transcribed</strong>, naming the mob. <strong>Nothing is uploaded.</strong> The parse happens in the page; an inventory names your character and lists what you own, and that stays yours. It refuses to score your gear: the file carries names, IDs and counts and <strong>no stats at all</strong>, so any rating would be invented. An item we do not recognise is reported as a gap in our catalogue, not in your bags"),
    dict(kind="Correction", date="11 Aug 2026", title="Six item names, and four we could finally spell",
         body="The dump is the game&rsquo;s own record of an item name, which beats any reading of a wiki. Six were wrong here: <em>A Dark Cauldron</em>, <em>Djarns Amethyst Ring</em>, <em>An Elven Charm Necklace</em>, <em>An Executioners Axe</em>, <em>Skull-shaped Barbute</em> and <em>Slaver&rsquo;s Lash</em> are Dark Cauldron, Djarn&rsquo;s Amethyst Ring, Elven Charm Necklace, Executioner&rsquo;s Axe, Skull-Shaped Barbute and Slaver`s Lash. <strong>And four items that had no page now have one.</strong> Where a loot cell elides a shared prefix we refused to guess the full name, so <em>Fire</em>, <em>Water</em>, <em>Greaves</em> and <em>Sleeves</em> sat as fragments. They are <strong>Torn Page of Mastery Fire</strong>, <strong>Torn Page of Mastery Water</strong>, <strong>Mithril Greaves</strong> and <strong>Embroidered Black Sleeves</strong>. The caution earned itself twice over: the format has no colon, and &ldquo;Sleeves&rdquo; beside an Embroidered Black Cape is a different garment, not the cape. Earth and Wind stay unnamed &mdash; we know the format now, but applying it to them would be a pattern inference rather than a reading"),
    dict(kind="Correction", date="11 Aug 2026", title="We counted one player&rsquo;s loot against the whole group&rsquo;s kills",
         body="Published this morning: a drop figure for Efreeti Lord Djarn that set one player&rsquo;s loot against the whole group&rsquo;s kills. <strong>A log records what its own character picked up</strong>, not what the corpse held, so the pieces that went to another player were missing from the total and the drop read as less reliable than it is. The <em>data</em> was never wrong &mdash; the sightings join has always read every log. The mistake was in a sentence typed beside it, which is the same fault as every other one this register records: a figure re-derived by hand next to a figure printed from data"),
    dict(kind="Correction", date="11 Aug 2026", title="Difficulty is the lowest tier that drops, not the commonest",
         body="We read a session&rsquo;s difficulty from the <code>+N</code> most items arrived at. It is the <strong>lowest</strong> <code>+N</code>, and the difference is not academic. Where the zone line states the tier independently, <strong>not one item drops below it</strong> &mdash; difficulty is a floor, and about an eighth of drops roll above it. The floor identifies the tier in every measured session; the commonest value does not. It is a roll and not a property of the item: <em>Fine Steel Rapier</em> drops at +1, +2 and +3, all at Awakened. <strong>The practical gain is small samples</strong> &mdash; three drops settle it, where a commonest value needs an evening. A bare item with no suffix had to start counting as <code>+0</code> for any of this to work, or every open-world session read as Awakened. <strong>No difficulty already published changed</strong>"),
    dict(kind="Correction", date="11 Aug 2026", title="Two names on the Nagafen&rsquo;s Lair roster",
         body="<strong>Magi Rokyl is Magus Rokyl.</strong> The measured log names him on both combat and loot lines, dropping the same Polished Mithril Mask the survey attributes to him, so a measured source corrects a read one. <strong>And we withdraw a merge made on 10 August.</strong> That day&rsquo;s note said we had &ldquo;merged one dragon spelled two ways&rdquo;: <em>Zordak Ragefire</em> and <em>Zordakalicus Ragefire</em>. They are not one entry spelled two ways. The survey gives them different levels, races, locations and behaviour &mdash; a level 60 non-aggressive human merchant, and a level 54 triggered lava dragon. One character in the Cleric epic, two things in the game. The merge pointed both rows at a single page, so whichever built last erased the other, and the merchant had no address for a day. He has one again. A shared surname is not a spelling variant"),
    dict(kind="Addition", date="11 Aug 2026", title="Sol B and The Hole, measured",
         body="<strong>Nagafen&rsquo;s Lair at Awakened</strong> and <strong>The Ruins of Old Paineel at Base and Awakened</strong> are measured for the first time. Both surveys carried rosters and neither carried a measured section. <strong>Efreeti Lord Djarn drops Golden Efreeti Boots, and an Amethyst Ring less often</strong> &mdash; recorded as seen, never as a rate. The multiclass-trash finding from Castle Mistmoore <strong>replicates in a second zone</strong>: <em>an imp protector</em> backstabs while casting Dry Bone Fire Burst, plus heals and a charm. Its melee averages 45 and its backstab 175, max 405, which is why no single average is printed for a mob that backstabs. <strong>At Base the same zone runs one kit per mob</strong>, not two &mdash; the capturer backstabs and never casts, the channeler heals and never backstabs. Class kits reach trash at Base; a mob carrying two of them remains an Awakened observation"),
    dict(kind="Addition", date="11 Aug 2026", title="A Learn hub, and search for everything else",
         body="Six Learn pages existed and the header&rsquo;s <em>Learn</em> link went to one of them, with the breadcrumb on every Learn page pointing back at that same article. There is a <a href=\"learn/index.html\">hub</a> now, driven by the same registry as the footer so the two cannot disagree. <strong>And the site is searchable.</strong> The only search covered items and named mobs &mdash; you could not find <em>Screaming Terror</em>, <em>voidling</em>, <em>mote</em> or <em>tier C</em> anywhere, including on the pages that explain them. <a href=\"search.html\">Search</a> covers the other 41 pages. The first build indexed 1,400 characters a page and still could not find Screaming Terror, which was the whole point; it indexes whole-page tokens now. Header and footer also lead with the same section for the first time"),
    dict(kind="Addition", date="11 Aug 2026", title="What we have actually watched drop",
         body="Every item page on this site &mdash; and on every competitor&rsquo;s &mdash; is a transcription of what a wiki says drops. Measured drops are the one thing nobody else has, and until now they lived at the bottom of one zone page and flowed nowhere. <strong>Named-to-item sightings now print on the item and named-mob pages.</strong> <strong>Seen, never a rate</strong> &mdash; a drop seen once is seen once. Of 501 distinct items observed dropping, 121 match a survey loot table; the other 380 are vendor trash and +N gear lines, which fall off anything and are not a gap in the catalogue. Joining the two estates needed a canonical name key that strips the +N tier and the leading article, because the roster writes <em>A Fallen Noble</em> and a log writes <em>a fallen noble</em>"),
    dict(kind="Correction", date="11 Aug 2026", title="One respawn ceiling was printing bare",
         body="Four zones mark their respawn with <code>&le;</code> because the 28 July patch lowered the maximum without publishing a figure. Crushbone&rsquo;s own note said to treat 9:00 as a pre-patch ceiling and it printed bare. Marked. <strong>And a contradiction is now recorded rather than carried:</strong> our Blackburrow note says the zone is not in that patch list, the register says it is, and the two renderings of the note we have seen name six dungeons and eleven. We do not know which, so the page says so"),
    dict(kind="Correction", date="11 Aug 2026", title="The retraction reached the header and not the row",
         body="An outside audit found the defect this site is most prone to, in its worst form yet. The placeholder question was settled at tier 1 and every affected survey grew a header saying <em>no placeholders here</em> &mdash; while the roster three lines below still read <strong>&ldquo;Placeholder is an earth elemental&rdquo;</strong> in bold, present tense. The header is authored; the rows are generated; nothing connected them. <strong>18 claims across 5 surveys are now struck as historical by the renderer</strong>, reading <code>placeholders_removed</code>, which already existed in the data and which nothing had ever read. One analysis paragraph built on the retracted model &mdash; a camp called &ldquo;the most frustrating&rdquo; because of a 10% spawn off two placeholders &mdash; has been corrected too"),
    dict(kind="Correction", date="11 Aug 2026", title="Eight items were never items",
         body="A loot cell reading <em>Mithril Vambraces</em> then <em>Greaves</em> means two pieces sharing a prefix; one reading <em>Torn Page of Mastery</em> then <em>Earth &middot; Water &middot; Fire &middot; Wind</em> means one item with four variants. Our splitter treated both separators the same, so <strong>Earth, Fire, Water, Wind, Skin, Sleeves, Greaves and &ldquo;pg. 3&rdquo; each got a page, a canonical URL and a share card.</strong> They are suppressed now and printed on their parent instead. We have not reconstructed the full names: the row elides a prefix and guessing it would invent an item. Also merged one dragon spelled two ways, and split a slash-joined pair of guards"),
    dict(kind="Correction", date="11 Aug 2026", title="Metadata was the last place hand-typed facts lived",
         body="Body counts were made to print from data on 10 August. The <code>&lt;head&gt;</code> was not, so four pages still advertised <em>ten surveyed dungeons</em> to Discord and to search results &mdash; which is the only text most readers ever see. Descriptions now derive from the same registry as the body, and <strong>the gate reads the head</strong>. The tools page also printed seven trackers over a grid of six, because the count came from the registry and the cards were hand-written; the seventh card exists now"),
    dict(kind="Addition", date="11 Aug 2026", title="Motes: spells scale doubled, items scale flat",
         body="A mote is worth <strong>2<sup>rank&minus;1</sup></strong> to a spell and <strong>exactly its rank</strong> to an item, and that one difference decides every mote decision. It means <strong>converting motes upward destroys item XP</strong> &mdash; two rank 5s are 10 item XP and the rank 6 they become is 6. Convert for spells, never to feed an item. From an infographic supplied as a developer release; <strong>the artefact is branded by a creator</strong>, so it is published T3 until someone shows otherwise. Three of its four testable claims match patch notes we hold. The fourth does not: it shows ten mote ranks where the 21 June note says the conversion construct accepts ranks 1 to 8"),
    dict(kind="Correction", date="11 Aug 2026", title="Every raid figure was logged twice",
         body="A second client&rsquo;s log of the same fights arrived, so every number on the difficulty ramp is now a measured range rather than a point. Two parses of one kill disagree by however much each client was out of range to see &mdash; <strong>between nothing and 3.2% here, with two fights matching exactly</strong>. That spread is the method&rsquo;s error bar. It also corrected us: <strong>we published ten self-heals at D4 and the second log shows one</strong>. The pattern &mdash; no healing below D3, healing at and above it &mdash; is in both logs independently, so the finding stands and the count does not"),
    dict(kind="Addition", date="11 Aug 2026", title="The difficulty ramp, measured on one boss at all five tiers",
         body="Master Yael measured at D0, D1, D2, D3 and D4, in the group instance of The Hole. <strong>The class kit widens at D3</strong> &mdash; direct damage and control up to D2, then healing, fear and damage over time from D3. He healed himself <strong>never at D0, D1 and D2, once at D3 and ten times at D4</strong>, which needs no inference about spell names: the log says <em>healed itself</em>. That is the largest gap this site has listed, and it lands exactly where the published claim said it would. Damage to kill ran 75,369 / 85,415 / 139,117 / 227,690 / 242,060 &mdash; <strong>an upper bound on hit points, not a measurement of them</strong>, because he heals"),
    dict(kind="Correction", date="11 Aug 2026", title="One sentence was on 446 pages",
         body="A site-wide sweep for repeated text found <strong>12,195 words of it</strong>, and almost all of it was boilerplate on the item and named-mob pages. One fifteen-word sourcing sentence appeared on all 446 item pages &mdash; 6,690 words of the same line, the largest single block of repeated text on the site &mdash; and two more ran to 2,400 between them. All three are now short lines that say the same thing, and the survey they point at was already linked directly above. <strong>9,386 words gone, not one fact with them.</strong> Repetition across three or more pages is down to 1,880 words, nearly all of it single lines that have to exist on each page"),
    dict(kind="Correction", date="11 Aug 2026", title="Accuracy said the same thing twice",
         body="The per-zone provenance section rendered a summary table <em>and</em> the ten prose blocks that table was built to replace, so four zones restated their own row in a paragraph underneath it. Those are gone and the rule they shared &mdash; infobox live, narrative prose imported &mdash; is stated once above the table. Eight blocks also carried survey markup pasted in, rendering a meaningless section number and putting an <code>h2</code> inside the zone&rsquo;s own <code>h3</code>. Both fixed. The rest of that section stays: it reads as repetitive but the ten blocks are only 8 to 30% alike, and the difference is the evidence"),
    dict(kind="Addition", date="11 Aug 2026", title="The Plane of Sky, measured and redrawn",
         body="Sky's teleporters form a <strong>ring</strong> &mdash; island 8 returns you to island 1 &mdash; so the six-boss circuit everyone runs is not a list to memorise, it is one and a half laps. The page is built on that, on the key chain, and on a thing nobody has published: <strong>the zone read from its own mesh</strong>. 21 separate bodies of walkable floor across <strong>2,878 units of height</strong>, drawn as a side elevation. It is deliberately unlabelled &mdash; the mesh says where every piece of floor is and cannot say which piece is island 4, and ten <code>/loc</code> readings would fix that permanently. The old page was one player's solo route framed by their trio and gear, which is a fact about a player rather than about the zone"),
    dict(kind="Addition", date="11 Aug 2026", title="Contributors are credited in one place now",
         body="Findings used to be credited inline, so a survey read a player's name in the middle of a sentence about loot. That buried the thanks and gave creators nothing back. Claims now carry what a reader needs to weigh them &mdash; the kind of source, the date, the tier badge &mdash; and <a href=\"credits.html\">every contributor is named once</a>, with a link to their own work where they have one. Wiki editor usernames stay inline: those are citations rather than credits, and the provenance test needs them"),
    dict(kind="Addition", date="11 Aug 2026", title="A planar gear tool, and 116 item records behind it",
         body="Your trio can wear planar armour from all three of its classes plus the two shared "
              "sets, so <strong>five sets compete for every slot</strong>. The tool shows that pool, "
              "ranks it by a named preset &mdash; highest AC, mana and casting, most total stats, "
              "clicky effects, resistances &mdash; and lets you lock a target per slot, two for "
              "wrist. <strong>No weights to configure.</strong> Built on 116 pieces mined from the "
              "item records, with 1,219 blank fields kept blank rather than filled with zeroes. "
              "The idea came from a guild member who did it by hand with an AI first &mdash; "
              "<a href=\"credits.html\">credited here</a>"),
    dict(kind="Correction", date="11 Aug 2026", title="The planar class-group split is gone",
         body="Our Fear and Hate surveys divided every drop into two class groups, following the "
              "imported wiki tables. <strong>A guild loot guide lists them merged</strong> &mdash; "
              "slot-specific, not group-specific &mdash; and adds that any of those mobs can drop "
              "the matching Lustrous Russet or Midnight Clad piece. It also moves a turmoil toad "
              "from Hands to Wrist. Both surveys corrected and flagged as one pre-launch source. <strong>The haunted chest question is now settled:</strong> two "
              "independent Legends-era accounts seven weeks apart, one post-launch, both say "
              "Lustrous Russet only, against the imported claim of any planar piece"),
    dict(kind="Addition", date="10 Aug 2026", title="Kedge Keep surveyed",
         body="Survey 13, and the highest ZEM on the site &mdash; <strong>139, "
              "or 185%</strong>, which the 23 June patch note singles out as deliberate: "
              "&ldquo;Kedge has retained its original modifier for those willing to brave the "
              "depths.&rdquo; <strong>Four class epics converge on Phinigel Autropos</strong> "
              "&mdash; Wizard, Bard, Rogue and Magician &mdash; which makes it the place to test "
              "whether the Fiery Avenger result generalises. The floor plan carries a "
              "caveat we have not needed before: our plans draw walkable floor, and this is a zone "
              "you swim through, so it under-draws where you can actually go"),
    dict(kind="Correction", date="10 Aug 2026", title="Two counts were typed instead of printed",
         body="The dungeon index headline read &ldquo;Ten zones, surveyed&rdquo; with thirteen in "
              "the ledger, and the 404 page offered &ldquo;Five trackers&rdquo; against a six-tool "
              "registry. Both were spelled out as words in templates, and every count check the "
              "build had matched digits only. Both now print from the data, and the gate reads "
              "words as well as numerals"),
    dict(kind="Addition", date="10 Aug 2026", title="Plane of Fear and Plane of Hate surveyed",
         body="Surveys 11 and 12, and the first two written knowing that almost everything "
              "published about them is Project 1999 text. Both carry armour tables by slot and "
              "class group, and Hate carries the ten minibosses mapped onto the trash each one "
              "upgrades. <strong>The floor plans are read from the game&rsquo;s own meshes.</strong> "
              "Hate separates into three levels and the middle one &mdash; ten units deep, 367 "
              "disconnected pieces &mdash; is the rooftops players cross with levitate to avoid "
              "ground aggro. No flattened map can show that, and no one else publishes it. "
              "Four published boss coordinates were checked against our own geometry and all four "
              "land on drawn floor"),
    dict(kind="Correction", date="10 Aug 2026", title="The plane boss pages are classic EverQuest",
         body="Checked against the wiki&rsquo;s revision API rather than its page footers. Every "
              "Fear and Hate boss page is a Project 1999 import &mdash; Cazic Thule and Innoruuk "
              "both from <code>imported&gt;CrazyPro</code>. The Cazic Thule strategy recommends "
              "&ldquo;several dozen melee and a dozen+ healers&rdquo; in a game that caps raids at "
              "8, and every published respawn timer describes an open-world spawn the 16 June patch "
              "note removed. One exception: Innoruuk carries 156,000 HP at D2 and 235,000 at D4, "
              "the only difficulty-tiered plane-boss figure published anywhere. It is a pre-launch "
              "beta edit with no stated method, so it prints badged and nothing is built on it"),
    dict(kind="Addition", date="10 Aug 2026", title="Every item and every named mob now has its own page",
         body="655 new addresses &mdash; <a href=\"items/index.html\">446 items</a> and "
              "<a href=\"named/index.html\">209 named mobs</a>, each carrying what we hold on it and "
              "linking back to the survey it was mined from. Until now all of it lived inside one "
              "search box, so there was nothing to bookmark, paste into guild chat or link to. "
              "The Index is unchanged and still the fastest way to filter"),
    dict(kind="Correction", date="10 Aug 2026", title="Item stats read off a shared table row",
         body="27 loot rows list several items behind a single stats cell, and splitting those rows "
              "copied the one stats line onto each item &mdash; so <em>Red Dragon Scales</em> "
              "carried a description of a tooth and a book of prayers. 90 items were affected. The "
              "stats now say they describe the row rather than the item"),
    dict(kind="Correction", date="10 Aug 2026", title="Two gaps closed, and neither was still open",
         body="<strong>Placeholder removals</strong> was answered by the developers&rsquo; own patch "
              "note, which names all eleven zones placeholders were removed from; it had been carried "
              "as unresolved since launch. <strong>Five missing maps</strong> was closed when "
              "<code>geometry.py</code> replaced the hand plots &mdash; all ten surveys have had a "
              "floor plan read from the game meshes since 10 August. What the plans still lack is "
              "room names, and that is what the gap says now"),
    dict(kind="Correction", date="10 Aug 2026", title="A third of the item catalogue had no class data",
         body="Building the levelling route surfaced it: <strong>160 of 452 items carried no class "
              "list</strong>, and every item in Castle Mistmoore and The Hole was affected. Three "
              "faults, all in the extractor. Some surveys head that column &ldquo;Classes&rdquo; "
              "and others &ldquo;Classes &amp; races&rdquo;, and an exact-match lookup returned "
              "nothing for the second kind. A <code>&lt;br&gt;</code> between the classes and the "
              "races was flattened away, turning &ldquo;WAR PAL RNG SHD&rdquo; into "
              "&ldquo;SHDall&rdquo; and hiding the last class on every such row. And worst, "
              "<strong>a cell the parser could not read defaulted to ALL</strong> &mdash; inventing "
              "permission for every class to use an item whenever the parse failed. Earthshaker "
              "read as usable by everyone; it is WAR PAL RNG SHD. The Index&rsquo;s class filter "
              "was silently dropping a third of the catalogue. 157 items still have no class list "
              "and now say so: they come from quest-component tables that carry no class column at "
              "all, which is a real absence rather than a parse failure"),
    dict(kind="Addition", date="10 Aug 2026", title="One character sheet, one link",
         body="The site had three save states &mdash; the race tracker, the Plane of Sky tracker, "
              "and the calculator sharing the race tracker&rsquo;s key. Three links to keep, three "
              "things to lose, and <strong>nobody keeps three links</strong>. The character sheet "
              "carries all of it in one address: name, race, primary class, trio, level, race "
              "unlock progress and Sky progress. Open that link on another machine and the sheet "
              "rebuilds &mdash; <strong>and so do both trackers</strong>, because the sheet writes "
              "their state back for them. Still no account and still nothing transmitted: "
              "everything after the <code>#</code> stays in the browser and is never sent here. "
              "<strong>What it deliberately does not do is decode the Sky bitfield.</strong> "
              "Parsing that structure out of the tracker gave 200 components where the tool itself "
              "reports 222, and a count that might be wrong is worse than no count, so the sheet "
              "shows the trio and links out for the detail. Epic progress is absent for the same "
              "reason &mdash; the site holds no structured epic data, and a checklist invented from "
              "loot tables would be a guess"),
    dict(kind="Addition", date="10 Aug 2026", title="Every page now has a share card and a canonical address",
         body="Zero of the site&rsquo;s 33 pages carried an <code>og:image</code>. EverQuest "
              "communities coordinate in Discord, and <strong>a link with no card is a link nobody "
              "opens</strong> &mdash; so every page we wrote was invisible at the exact moment "
              "somebody tried to share it. There are 17 cards now, drawn from the zone data itself: "
              "name, level band, ZEM, respawn and verification state, so a card cannot drift from "
              "the page it represents. <strong>Also fixed: no page had a canonical address.</strong> "
              "Every internal link ends in <code>.html</code> and the host redirects it to the "
              "extensionless form, which gave every page two addresses and let a search engine pick. "
              "32 of 33 now name the right one &mdash; the 404 page deliberately does not. And "
              "fifteen standalone pages had no description at all, so their embeds would have "
              "carried a title and an image and no sentence; they take their subtitle now, with the "
              "level band and respawn appended"),
    dict(kind="Correction", date="10 Aug 2026", title="Placeholders: the answer was in the patch notes the whole time",
         body="The developer patch note removes placeholders by name from <strong>eleven "
              "dungeons</strong> &mdash; The Hole, Nagafen&rsquo;s Lair, Lower Guk, Lair of the "
              "Splitpaw, The Warrens, Castle Mistmoore, Upper Guk, Crushbone, Befallen, Blackburrow "
              "and Najena. That is every zone this site surveys, plus Upper Guk. <strong>Named spawn "
              "every cycle and every inherited spawn percentage on the site is historical.</strong> "
              "We carried this as an open question for a day, weighing a wiki category page against "
              "our own play, while the answer sat in a tier 1 source nobody had gone back to read. "
              "The percentages stay printed rather than deleted &mdash; deleting what a source says "
              "is how a record stops being checkable &mdash; but every survey now says plainly that "
              "they describe nothing about the zone now. <strong>The same patch note lowers maximum "
              "respawn times and publishes no figures</strong>, so every respawn here remains a "
              "pre-patch ceiling and is labelled as one"),
    dict(kind="Correction", date="10 Aug 2026", title="Ten source warnings become one table",
         body="The Accuracy page carried ten near-identical prose blocks, each stating the same "
              "four facts about a wiki page in a different order. They are one sorted table now, "
              "with a revision column: zone, last edited, revision id, editor, whether the page "
              "began as a Project 1999 import, and what that means for the survey. <strong>Where a "
              "field was never established the cell says &ldquo;not recorded&rdquo;</strong> rather "
              "than sitting empty, because an empty cell reads as nothing to report and that is a "
              "different claim. Thirteen cells say it. Also removed: 355 words arguing that the "
              "hand-drawn plots were internally consistent, which was a defence of drawings retired "
              "the same day"),
    dict(kind="Correction", date="10 Aug 2026", title="The plates are retired, and kept",
         body="This site began as ten hand-built coordinate plots. Every named mob&rsquo;s "
              "<code>/loc</code> read off the wiki, transformed into page space and drawn by hand "
              "with a numbered legend beside it. The pages were called <em>plates</em> because that "
              "is what they were. <strong>They are redundant now.</strong> The floor plans derived "
              "from the game&rsquo;s own mesh archives are better in every direction that matters: "
              "the walls are the game&rsquo;s walls rather than an outline drawn around some dots, "
              "the storeys separate, the named filter by storey, and every coordinate is checked "
              "against walkable floor at build time &mdash; which is how six impossible Najena "
              "positions were caught and withheld. The hand plots could not have caught them, "
              "because they had nothing to check against. So the guides are <strong>Dungeon "
              "surveys</strong> from today, and the ten original plates move whole to "
              "<a href=\"archive/index.html\">the archive</a>, stored exactly as they last "
              "shipped. Not deleted and not tidied: they are the record of how the survey was done "
              "before it could be done properly, and anyone who wants to judge whether we improved "
              "or merely changed can put the two side by side"),
    dict(kind="Addition", date="10 Aug 2026", title="Is it still true? &mdash; the register of inherited advice",
         body="Almost everyone playing Legends played EverQuest, and arrives carrying twenty-five "
              "years of habit. Some of it holds and some was quietly replaced, and <strong>the wiki "
              "cannot tell you which is which, because large parts of the wiki are the old "
              "text</strong>. One entry per piece of inherited advice, each with its evidence, its "
              "date, and what it would take to settle it. Six to start: multiclass, difficulty not "
              "raising mob levels, placeholders in the revamped dungeons, the Per-Level Hunting "
              "Guide, underwater weapon types, and whether Paragon of Spirit stacks with Clarity. "
              "<strong>Three are open, and that is the normal state rather than a failure.</strong> "
              "The last of those exists because an AI assistant answered the stacking question by "
              "citing eqlwiki's Buff Lines page for &ldquo;slots nine, ten and eleven&rdquo;. That "
              "page describes slots 1&ndash;8 and a Layer 2, never mentions Paragon of Spirit, and "
              "the spell has no wiki page at all &mdash; the URL returns 404. Asked to be more "
              "certain, the same tool returned more sources and more specific detail: confidence "
              "rose, evidence did not. That pattern is worth more than the spell"),
    dict(kind="Correction", date="10 Aug 2026", title="Najena's spawn percentages, and a T5 number in a structured field",
         body="Two faults on the flagship plate, both found by an outside reader and both worse than "
              "reported. <strong>The header carried a 19:00 zone respawn and argued it was "
              "current.</strong> It is not a zone figure: it comes from the wiki zone page's prose, "
              "on a page carrying <code>{{Classic Era}}</code>, so by our own standard it is import "
              "text. The infobox on that same page gives the zone spawn timer as <strong>4:50</strong>, "
              "corrected there on 4 August. The ~19 minute figure is a per-mob cycle and is now "
              "labelled as one. Publishing a tier 5 prose number in a structured field and then "
              "reasoning about whether it was current is the exact mistake this site exists to "
              "catch. <strong>Separately, the spawn percentages are almost certainly meaningless.</strong> "
              "Four sources say the revamped dungeons have no placeholders &mdash; the 23 June patch "
              "note promising &ldquo;a striking lack of placeholders&rdquo;, eqlwiki's Named Mobs "
              "category, and first-hand play at The Tenderizer across consecutive cycles with no "
              "placeholder seen. Only "
              "individual wiki mob pages still describe placeholders, in classic text nobody has "
              "revisited. The figures stay printed and struck through: deleting them would hide what "
              "the source says. A log across several cycles at one camp settles it outright. "
              "<strong>Drelzna also gained three drops</strong> her wiki record carries and this "
              "plate never did &mdash; Dark Elf Parts, Bronze Greaves and Tentacle Whip"),
    dict(kind="Correction", date="17 Aug 2026", title="Eight named bosses, not raid bosses generally",
         body="The raid-access explainer read the 16 June patch note as a rule about raid bosses "
              "as a class. <strong>It names eight, individually</strong> &mdash; Maestro of Rancor, "
              "Innoruuk, Cazic Thule, Fright, Terror, Dread and a dracoliche &mdash; and every one "
              "of them is a Fear or Hate boss. The Plane of Sky's bosses stand in the open zone, "
              "which is the counter-example the broader reading could not survive. The page states "
              "the narrower claim now, and the note that it once said otherwise moved here, which "
              "is where a correction belongs."),
    dict(kind="Correction", date="17 Aug 2026", title="Tier C withdrawn: a first-hand report is not a tier",
         body="A tier was added on 10 August for named first-hand reports, and it should not have been. "
              "<strong>It was generalised from a single event</strong> &mdash; one first-hand "
              "confirmation of one thing &mdash; and one event is not a rank on a "
              "scale. The scale exists to rank <em>readings of documents</em>, and someone telling you what "
              "happened to them last night is not that. It never belonged on the ramp. "
              "<strong>Nothing published is retracted and no evidence is lost.</strong> The twenty claims "
              "that carried the badge already named who reported them and when, in the sentence itself, "
              "which is where that belongs: a reader sees the provenance without having to learn a badge "
              "first. What changes is that they no longer wear a rank they had not earned."),
    dict(kind="Addition", date="10 Aug 2026", title="Tier C, for a first-hand report that is not a log",
         body="The source scale ran M, 1, 2, 3, 4, 5, and a named player saying &ldquo;I did this last "
              "night and it did not work the way the wiki says&rdquo; fitted none of them. It is not "
              "tier M &mdash; nothing was parsed, and recollection is not a log. It is not 3 to 5, "
              "which are readings of documents. <strong>Tier C sits below M and above 3: first-hand, "
              "named, dated, unconfirmed</strong>, and every claim carrying it publishes who reported "
              "it, when, what would confirm it, and that it has not been. A Tier C claim never becomes "
              "fact by repetition &mdash; it is confirmed and moves, or it stays C visibly. "
              "<strong>This applies to us as well:</strong> a parsed log is tier M because an instrument read "
              "them; a recollection is not, and exempting the site from its own scale would be the fastest way to corrupt "
              "the scale"),
    dict(kind="Correction", date="9 Aug 2026", title="A verification gate that could not be passed",
         body="Gate 3 of the verification standard asked that coordinates be collision-checked "
              "against the room list. <strong>There is no room list.</strong> Across the five zones "
              "then held at <em>partial</em>, not one room carried a coordinate and 9 of 209 named "
              "mobs named a room or floor at all &mdash; so the check had no left-hand side and "
              "could not be failed, passed or attempted. Five zones sat waiting on it, which read as "
              "work remaining when the truth was that the test did not fit our data. <strong>Gate 3 "
              "is now the geometry check</strong>: every coordinate must land within 120 units of "
              "the walkable floor extracted from the game's own mesh files, counted at build time "
              "rather than typed. It is the stronger test for whether a position is real &mdash; it "
              "is how six impossible Najena coordinates were found and withheld &mdash; and the "
              "weaker one for whether a position matches the room its note names. That trade is "
              "stated in the standard rather than buried. Closing the change, <strong>The Warrens "
              "cleared gate 1</strong>: its page was fetched in full for the first time and all 17 "
              "named mobs, the 6:40 respawn and the 4&ndash;25 level range all agree; and "
              "<strong>Blackburrow gained the reading key</strong> it was the only plate of ten to "
              "lack. All ten zones are now fully verified, 176 of 176 coordinates on drawn floor"),
    dict(kind="Source refresh", date="9 Aug 2026", title="The Hole, three weeks behind its own source",
         body="The plate cited the wiki as last edited 15 July. Taken from the API rather than the "
              "page footer, it had been edited <strong>six times on 8 August</strong>, the last at "
              "21:25. Re-compared in full: every named mob the wiki lists is on the plate and the "
              "respawn still agrees at 7:48, so nothing was wrong &mdash; but <strong>Slizik the "
              "Mighty gained a coordinate</strong>, 372, &minus;88, where the plate had only "
              "&ldquo;back of the Ratman Jail&rdquo;. It lands 10 units from drawn floor, so it "
              "checks out against the zone geometry as well as against the source"),
    dict(kind="Correction", date="8 Aug 2026", title="Befallen's respawn, and a source two months stale",
         body="Two faults on one plate, both found by taking the wiki's edit history from the API "
              "instead of its page footer. <strong>The plate said its source was last edited 7 June "
              "2026. It was last edited 5 August</strong>, revision 166594 &mdash; and the plate "
              "reasoned from the wrong date, telling readers the page &ldquo;cannot reflect anything "
              "after 7 June&rdquo; when it postdates launch and gained the Ebon Scythe on 5 August. "
              "Separately, <strong>the prose still gave the respawn as 4:27 in four places while "
              "the zone data said 4:30</strong>, corrected from the wiki on 1 August &mdash; the "
              "page and the data driving it disagreed. The roster itself checks out: all 15 named "
              "mobs on the wiki are on the plate"),
    dict(kind="Addition", date="8 Aug 2026", title="Kelynn, missing from the Crushbone roster",
         body="A named mob the plate never carried. Found by comparing our roster against the "
              "eqlwiki Crushbone page line by line during a verification pass: 16 named on the "
              "wiki, 18 on our plate, and <strong>Kelynn was on theirs and not ours</strong>. "
              "Level 9, 12% spawn, at 3, 387. The same comparison found <strong>no coordinate "
              "mismatches at all</strong> across the fifteen named mobs both sources carry, and "
              "the zone respawn agreeing at 9:00"),
    dict(kind="Correction", date="8 Aug 2026", title="Six Najena coordinates that sit outside Najena",
         body="Rathyl, Ekeros, BoneCracker, Officer Grush, Trazdon and A Visiting Priestess are "
              "recorded on eqlwiki at positions south of the zone&rsquo;s own extent, by between 57 and "
              "513 units &mdash; outside the dungeon. Najena&rsquo;s geometry runs from &minus;168 to "
              "546 on the north&ndash;south axis, measured from the map file EverQuest Legends installs "
              "with the game; two community map sets drawn independently agree to within two units. "
              "The east&ndash;west value is right in every case and only the north&ndash;south value is "
              "out, which points at a single column rather than at noise. Our transcription matches the "
              "source exactly, so this is the source being wrong rather than us misreading it. The six "
              "are withheld from the survey plot and listed with the reason instead. <strong>No "
              "replacement figure is published, because none is sourced</strong> &mdash; the official "
              "map carries no mob positions, so one <code>/loc</code> reading per mob closes it"),
    dict(kind="Correction", date="8 Aug 2026", title="A coordinate range read as a coordinate",
         body="A hiding gnoll in Lair of the Splitpaw is recorded as &ldquo;718&ndash;800, "
              "212&ndash;236&rdquo; &mdash; a span it appears across, not a point. The survey plot read "
              "the two ends as a north&ndash;south and east&ndash;west pair and drew it 464 units "
              "outside the zone. Ranges now join the list of mobs that vary by spawn point rather than "
              "being placed"),
    dict(kind="Correction", date="8 Aug 2026", title="The Eye of Veeshan's stat block",
         body="We published 32,000 hit points and 865 damage a swing as though they were EverQuest "
              "Legends figures. They are not. The hit points come from an eqlwiki page whose oldest "
              "revision is 25 March 2026 by an account named <code>imported&gt;Kistraxx</code> &mdash; "
              "four months before the game launched. The melee figure is contradicted inside eqlwiki "
              "itself, which gives 865 on one page and 200 on another. And the stat block lists the "
              "Eye as a single class at level 70, where Legends raid bosses run three classes from D3. "
              "Both figures now carry a T5 badge and the tanking section no longer reasons from either"),
    dict(kind="Correction", date="8 Aug 2026", title="Four respawn timers",
         body="The Hole read 21:30; eqlwiki replaced that with 7:48 on 14 July, two weeks before we "
              "captured the older value &mdash; it was stale on arrival. Befallen 4:27 to 4:30, Najena "
              "19:00 to 4:50, and Crushbone and Blackburrow gain figures they previously lacked. Each "
              "now records the revision, date, editor and comment behind it. Lower Guk's change was "
              "deliberately not adopted: the wiki raised it to 11:00, but the 28 July patch says that "
              "zone's respawn was <em>lowered</em>, and that contradiction is unresolved"),
    dict(kind="Correction", date="7 Aug 2026", title="Item count on The Index",
         body="The page described itself as holding &ldquo;389 items&rdquo; while the index it shipped "
              "held 452, and its own counter said 452 on screen. 389 was never correct at any point. "
              "Every count on the site is now printed from the mined data rather than typed by hand, "
              "so the sentence and the tool cannot disagree again"),
    dict(kind="Correction", date="6 Aug 2026", title="Verification counting",
         body="Front page claimed 8 of 10 plates verified. By the project&rsquo;s own three-gate "
              "standard it is 5. Corrected, and the open gate is now named per zone"),
    dict(kind="Correction", date="6 Aug 2026", title="Tracker state handling",
         body="Changes made in the trio builder were never saved, so reloading restored the previous "
              "trio. Reset also left the trio and the calculator selections untouched. Both trackers "
              "now have separate <em>Clear ticks</em> and <em>Start over</em> actions"),
    dict(kind="Correction", date="6 Aug 2026", title="Primary-slot logic",
         body="Calculator no longer suggests demoting a class you require in the primary slot"),
    dict(kind="Source refresh", date="5 Aug 2026", title="Race unlock data",
         body="Rebuilt against Alanna&rsquo;s guide revision 166686"),
    dict(kind="Addition", date="6 Aug 2026", title="Site launch",
         body="Ten plates, five maps, three tools, first raid encounter"),
]

TONE = {"Correction": "var(--ok)", "Addition": "var(--bone)", "Source refresh": "var(--instr)"}

# The three-letter stamp on the change log rows.
TAG = {"Correction": "FIX", "Addition": "NEW", "Source refresh": "DAT"}
