"""Fetch the four faces from Google once, so no reader ever fetches them again.

    python3 _build/fetchfonts.py

HAND-RUN, LIKE geometry.py AND ogcards.py. It needs the network, and a rebuild
must work on a machine that has none. Its output — public/assets/fonts/ and the
stylesheet beside it — is committed.

WHY THIS EXISTS
---------------
715 of the site's 717 pages fetched their typefaces from Google, which disclosed
every reader's IP address to Google before anything rendered. We had published
that exact criticism about a collaborator's application while doing it at scale
ourselves, and several of the pages doing it printed "Nothing transmitted".

Served from our own origin the disclosure stops existing. That is the fix; the
copy split is the honest description of the interval before it landed.

WHAT IT DOES, AND WHY IT IS A COPY RATHER THAN A CHOICE
-------------------------------------------------------
It asks Google for the same stylesheet the pages asked for, with a browser user
agent so the answer is woff2 rather than ttf. That response is a set of
`@font-face` blocks, each carrying a `unicode-range`. It downloads every file
those blocks reference and rewrites the `src` to a local path, changing nothing
else.

**Reproducing Google's own subsetting is the point.** A hand-rolled subset would
render differently, and the difference would be invisible until some page needed
a glyph the subset dropped. U+2212 MINUS SIGN is the specific hazard here: the
site uses it in every coordinate, 141 times in one file alone, and it lives in
Google's `latin` range. Taking their ranges verbatim means a character that
renders today renders tomorrow.

WHAT WE MAY AND MAY NOT CALL THEM
---------------------------------
All four are SIL Open Font License 1.1. Serving an UNMODIFIED file under its own
name is fine — OFL clause 3 restricts Reserved Font Names only for a Modified
Version, and a byte-identical copy is not one. This is why the files are taken
whole rather than subsetted here: subsetting would make a Modified Version and
force a rename, which is exactly why the Lockouts bundle ships "EQLS Mono" and
"EQLS Condensed". We take no such step and so keep the real names.
"""
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

OUT = 'public/assets/fonts'
CSS = 'public/assets/fonts/fonts.css'

# Exactly the families and weights the pages asked Google for. Read from
# _partials.py rather than typed, so a face added there cannot be missed here.
PARTIALS = open('_build/_partials.py', encoding='utf-8').read()
FAMILIES = re.findall(r'family=([^&"\']+)', PARTIALS)
if not FAMILIES:
    sys.exit('fetchfonts: found no family= in _build/_partials.py')

# A modern browser UA, or Google answers with ttf and the files are three times
# the size for no gain.
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode('utf-8')


def main():
    url = ('https://fonts.googleapis.com/css2?'
           + '&'.join(f'family={f}' for f in FAMILIES) + '&display=swap')
    print(f'fetchfonts: asking Google for {len(FAMILIES)} families')
    css = get(url)

    os.makedirs(OUT, exist_ok=True)
    seen = {}
    total = 0

    def local(m):
        nonlocal total
        remote = m.group(1)
        if remote in seen:
            return f"url('{seen[remote]}')"
        # Name the file after the family, weight and subset that the block
        # around it declares, so a human can tell them apart on disk.
        blob = get(remote, binary=True)
        stem = remote.rstrip('/').split('/')[-1]
        name = re.sub(r'[^A-Za-z0-9._-]', '-', stem)
        if not name.endswith('.woff2'):
            name += '.woff2'
        open(os.path.join(OUT, name), 'wb').write(blob)
        seen[remote] = name
        total += len(blob)
        return f"url('{name}')"

    css_local = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", local, css)

    remaining = re.findall(r'https?://', css_local)
    if remaining:
        sys.exit(f'fetchfonts: {len(remaining)} remote reference(s) survived the '
                 f'rewrite — refusing to write a stylesheet that still fetches')

    header = (
        '/* The four faces, served from this origin.\n'
        ' *\n'
        ' * Generated by _build/fetchfonts.py from the same Google stylesheet the\n'
        ' * pages used to request at load. The @font-face blocks and their\n'
        ' * unicode-range values are Google\'s, unmodified; only the src URLs are\n'
        ' * rewritten to local files. Reproducing their subsetting exactly is\n'
        ' * deliberate: a hand-rolled subset would render differently, and the\n'
        ' * difference would stay invisible until a page needed a glyph it had\n'
        ' * dropped. U+2212 MINUS SIGN is the one that would have bitten - the\n'
        ' * site prints it in every coordinate.\n'
        ' *\n'
        ' * The files are byte-identical copies, so they are not Modified Versions\n'
        ' * and OFL 1.1 clause 3 does not restrict their names. Licences and\n'
        ' * copyright notices are in LICENSES.md beside them.\n'
        ' *\n'
        ' * DO NOT EDIT. Re-run python3 _build/fetchfonts.py.\n'
        ' */\n')
    open(CSS, 'w', encoding='utf-8', newline='\n').write(header + css_local)

    print(f'fetchfonts: {len(seen)} file(s), {total / 1024:.0f} KB, '
          f'stylesheet {os.path.getsize(CSS) / 1024:.1f} KB')
    print(f'fetchfonts: 0 remote references remain in {CSS}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
