"""public/assets/plans/<slug>.svg — one shared locator plan per zone.

    python3 _build/plans.py      # run from build.sh, before build17.py

WHY A FILE PER ZONE RATHER THAN INLINE SVG
------------------------------------------
674 of this site's 723 pages are item and named-mob pages, and until now not
one of them carried a single graphic. They are the pages a search engine lands
a stranger on, and they looked like database rows.

Inlining a zone drawing into each would have cost roughly 4.7 MB across the
site and re-sent the same drawing on every page view. Thirteen standalone SVGs
cost 13 files, are fetched once, and are then served from cache for every other
page in that zone — which is exactly how a reader browses these: several items
from the same dungeon in a row.

WHAT IT DRAWS
-------------
The zone's walkable floor from the game's own mesh, stroked in the zone's
permanent accent. The viewBox is in the game's own page coordinates, which is
what lets a page put a mark on it: `bounds` is written alongside so any
generator can turn a recorded `/loc` into a percentage without knowing anything
about the geometry.

ORIENTATION, WHICH IS NOT OBVIOUS
---------------------------------
EverQuest's `/loc` returns **Y, X, Z**, and the site's convention is north up
the page and west to the left, so +Y is north and +X is west and BOTH axes
invert into page coordinates: a mob at `/loc 353, 105` draws at (-105, -353).
_build/geometry.py already stores the floor lines in that same inverted space,
which is why the two can be drawn on one viewBox at all. Getting this wrong
puts every mark in the diagonally opposite corner of the map, which looks
plausible enough to ship.
"""
import os, sys, json, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

OUT_DIR = 'public/assets/plans'
# Enough to read the shape at a glance without shipping every stub.
MAX_PATHS = 70


def main():
    GEO = json.load(open('assets/zone-geometry.json', encoding='utf-8'))
    Z = json.load(open('assets/zones-index.json', encoding='utf-8'))
    accent = {z['slug']: z['accent'] for z in Z}
    os.makedirs(OUT_DIR, exist_ok=True)

    bounds = {}
    total = 0
    for slug, g in GEO.items():
        lines = [ln for layer in g['layers'] for ln in layer['lines'] if len(ln) > 1]
        if not lines:
            continue
        xs = [p[0] for ln in lines for p in ln]
        ys = [p[1] for ln in lines for p in ln]
        x0, x1 = min(xs), max(xs)
        y0, y1 = min(ys), max(ys)
        # A little air so a mark sitting on the outer wall is not clipped in half.
        pad = max(20.0, max(x1 - x0, y1 - y0) * 0.03)
        x0, y0, x1, y1 = x0 - pad, y0 - pad, x1 + pad, y1 + pad
        w, h = x1 - x0, y1 - y0

        # Longest first: the silhouette matters more than the stubs.
        lines.sort(key=len, reverse=True)
        keep = lines[:MAX_PATHS]

        # Stroke width is a fraction of the drawing rather than a fixed value,
        # because these zones differ by 20x in extent and one width would be a
        # hairline on Lower Guk and a crayon on Kedge Keep.
        sw = max(w, h) / 520

        paths = []
        for ln in keep:
            pts = []
            for p in ln:
                xy = (round(p[0], 1), round(p[1], 1))
                if not pts or xy != pts[-1]:
                    pts.append(xy)
            if len(pts) < 2:
                continue
            paths.append('M' + ' L'.join(f'{x},{y}' for x, y in pts))

        col = accent.get(slug, '#C9922E')
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" '
               f'viewBox="{x0:.0f} {y0:.0f} {w:.0f} {h:.0f}" '
               f'role="img" aria-label="Floor plan of {slug}, from the game mesh">'
               f'<g fill="none" stroke="{col}" stroke-width="{sw:.2f}" '
               f'stroke-linejoin="round" stroke-linecap="round" opacity="0.85">'
               + "".join(f'<path d="{d}"/>' for d in paths)
               + '</g></svg>')
        open(os.path.join(OUT_DIR, slug + '.svg'), 'w',
             encoding='utf-8', newline='\n').write(svg)
        bounds[slug] = dict(x0=round(x0, 1), y0=round(y0, 1),
                            w=round(w, 1), h=round(h, 1), paths=len(paths))
        total += len(paths)

    doc = {
        '_comment': [
            'Bounds of each zone plan in public/assets/plans/, in the game page',
            'coordinate space (+Y north, +X west, both inverted -- see plans.py).',
            'A generator turns a recorded /loc "Y, X" into a percentage with:',
            '   left = (-X - x0) / w,  top = (-Y - y0) / h',
            'Generated by _build/plans.py - do not hand-edit.',
        ],
        'zones': bounds,
    }
    json.dump(doc, open('assets/zone-plan-bounds.json', 'w',
                        encoding='utf-8', newline='\n'), indent=1)
    print(f"plans: {len(bounds)} zone plans written, {total} paths, "
          f"{sum(os.path.getsize(os.path.join(OUT_DIR, s + '.svg')) for s in bounds) // 1024} KB total")
    return 0


# THE MINUS SIGN, AND THE RANGE. Both of these are build6.py's hard-won
# conventions and both were re-learned the expensive way here on 16 Aug 2026.
#
# 141 of the recorded coordinates use U+2212 MINUS SIGN rather than ASCII
# hyphen. A plain `-?\d+` reads every one of them as POSITIVE, which put marks
# in the diagonally opposite corner of the map — 46 of 60 checked positions
# disagreed with the zone's own floor plan, by up to 1,508 units, and every one
# of them looked perfectly plausible sitting on a drawing.
#
# And a range is not a coordinate: "718–800, 212–236" is a span the mob appears
# across, and reading its two ends as a Y,X pair plots a mob that is not there.
NUM = re.compile(r'[-−]?\d+(?:\.\d+)?')
RANGE = re.compile(r'\d\s*[–—]\s*\d')


def locate(bounds, loc):
    """A recorded `/loc` string to (left%, top%) on that zone's plan, or None.

    Kept here beside the transform it inverts, so a caller cannot get the axis
    order wrong independently of the file that wrote the viewBox.
    """
    if not loc or RANGE.search(loc):
        return None
    v = [t.replace('−', '-') for t in NUM.findall(loc)]
    if len(v) < 2 or not bounds:
        return None
    y, x = float(v[0]), float(v[1])
    px, py = -x, -y
    left = (px - bounds['x0']) / bounds['w'] * 100
    top = (py - bounds['y0']) / bounds['h'] * 100
    if not (0 <= left <= 100 and 0 <= top <= 100):
        return None          # off the drawn floor; a mark there would be a lie
    return round(left, 2), round(top, 2)


if __name__ == '__main__':
    sys.exit(main())
