"""assets/sightings.json — what we have actually watched drop.

    python3 _build/sightings.py        # run from build.sh; reads assets/measured.json

WHY THIS IS THE POINT OF THE PARSER
-----------------------------------
Every item page on this site is a transcription of what eqlwiki says drops. So
is every competitor's. The one thing we hold that nobody else does is a parsed
record of what we *saw* drop, and until now it lived in one section at the
bottom of one zone page and flowed nowhere.

This joins it. Where a mob in our logs matches a named mob in a survey roster,
and an item it dropped matches that survey's loot table, the pairing becomes a
tier M sighting printed on both pages: "seen dropping, 2 sessions, 8 Aug 2026."

A SIGHTING IS NOT A RATE
------------------------
One session is a sample. A drop seen once is seen once. Nothing here divides by
kills, and nothing here is a percentage - the count is how many times we watched
it happen, which is strictly more than the wiki offers and is not the same claim
as "how often it happens".

WHAT IS DELIBERATELY NOT PUBLISHED
----------------------------------
Of 501 distinct items observed dropping, 121 match a survey loot table. The rest
are vendor trash and `+N` gear lines - Rusty Long Sword, Ringmail Pants, Amber,
Pearl, Topaz - which fall off anything, exist to be sold, and are not tracked by
anyone for good reason. They are not published, not counted on the pages, and
not treated as a gap in the catalogue: the catalogue is right to omit them.

TWO NORMALISATIONS, BOTH LOAD-BEARING
-------------------------------------
`+N` is an upgrade tier, not part of the name: "Fine Steel Rapier +2" and "Fine
Steel Rapier" are one item. And a leading article is noise between data estates:
the roster writes "A Fallen Noble", a log writes "a fallen noble". Matching on a
key that strips both is the canonical name key an outside audit correctly said
had to exist before any of this could be joined.
"""
import os, re, json, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)


def key(s):
    """The canonical name key shared by the roster, the log tables and the catalogue."""
    s = re.sub(r'\s*\+\d+\s*$', '', s or '')
    s = re.sub(r'^(a|an|the)\s+', '', s.strip(), flags=re.I)
    return re.sub(r'[^a-z0-9]+', '', s.lower())


def main():
    try:
        M = json.load(open('assets/measured.json', encoding='utf-8'))
    except (OSError, ValueError):
        print('sightings: no assets/measured.json, skipped')
        return
    IX = json.load(open('assets/index-data.json', encoding='utf-8'))

    items = {}
    for i in IX['items']:
        if i.get('kind') != 'fragment':
            items.setdefault(key(i['n']), i['n'])
    named = {}
    for n in IX['named']:
        named.setdefault(key(n['n']), n['n'])

    pair = collections.defaultdict(lambda: {'n': 0, 'sessions': []})
    unmatched = 0
    for s in M:
        stamp = {'date': s.get('date'), 'zone': s.get('zone'),
                 'difficulty': s.get('difficulty'),
                 'label': s.get('difficulty_label'),
                 'character': s.get('character')}
        for mob, rec in (s.get('mobs') or {}).items():
            mk = key(mob)
            for item, count in (rec.get('loot') or {}).items():
                ik = key(item)
                if ik not in items:
                    unmatched += count
                    continue
                if mk not in named:
                    continue
                p = pair[(named[mk], items[ik])]
                p['n'] += count
                if stamp not in p['sessions']:
                    p['sessions'].append(stamp)

    by_named = collections.defaultdict(list)
    by_item = collections.defaultdict(list)
    for (mob, item), v in sorted(pair.items(), key=lambda kv: (-kv[1]['n'], kv[0])):
        by_named[mob].append({'item': item, 'n': v['n'], 'sessions': v['sessions']})
        by_item[item].append({'mob': mob, 'n': v['n'], 'sessions': v['sessions']})

    out = {
        '_comment': [
            'Observed drops, joined to the surveys. A count, never a rate.',
            'Vendor trash and +N gear lines are excluded and are not a catalogue gap.',
            'Generated by _build/sightings.py - do not hand-edit.',
        ],
        'by_named': dict(by_named),
        'by_item': dict(by_item),
        'pairs': len(pair),
        'excluded_trash_drops': unmatched,
    }
    json.dump(out, open('assets/sightings.json', 'w', encoding='utf-8',
                        newline='\n'), indent=1)
    print(f"sightings.json: {len(pair)} named-to-item pairs across {len(by_named)} mobs "
          f"and {len(by_item)} items ({unmatched:,} trash drops excluded)")


if __name__ == '__main__':
    main()
